# Generated by Django 3.1.5 on 2021-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210117_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Default.png', upload_to='products_pics'),
        ),
    ]
